version: "3.3"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    depends_on:
      - mysql
    networks:
      - red1


  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'numeros'
      MYSQL_USER: 'andres'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - red1

volumes:
  mysql_volume:
networks:
    red1:
      driver: bridge